camera0: 0
camera1: 1 #line 67 in calib.py hardcoded
frame_width: 1280
frame_height: 720
mono_calibration_frames: 50
stereo_calibration_frames: 50
view_resize: 2
checkerboard_box_size_scale : 0.99
checkerboard_rows: 6
checkerboard_columns: 9
cooldown: 20
